### ISSUE TITLE
".rb" missing in a command (TodoList)

### ISSUE THREAD

**Issue by kompu** [rgordeev/ruby-assignments01#10]
Error in line:
`$ rspec spec/assignment_spec -e rq02.1`

> Error:cannot load such file -- /ruby-assignments01/assignment05-todolist/spec/assignment_spec (LoadError)

Work line:
`$ rspec spec/assignment_spec.rb -e rq02.1`

**Comment by rgordeev** [comment]
Thanks a lot! 
fixed it.
