### ISSUE TITLE
assignment5-todolists/spec/relations_assignment_spec.rb - spec "rq07b" throws undefined method

### ISSUE THREAD

**Issue by Hedrig** [rgordeev/ruby-assignments01#13]
Этот тест в строке "subject(:dbUser) { User.where(username:"rich").first }" ищет пользователя с именем "rich". Проблема в том, что:
1) Перед своим выполнением спек rq07 вытер всю таблицу users через User.destroy_all, поэтому даже если вышеуказанный пользователь прописан в seed-файле, найден он не будет.
2) Спек rq07a, идущий перед rq07b, не добавляет нужного пользователя - только пользователей "goodUser" (password = "mux833c") и "test" ("goodPw!!").
В результате where возвращает NilClass, и тест не проходит, выбрасывая ошибку "undefined method 'authenticate' for NilClass".
Прошу объяснить, как выполнять это задание, или внести исправления в relations_assignment_spec.rb.

**Comment by rgordeev** [comment]
oh my gosh! That's my fault. Hope, this will help you 
https://github.com/rgordeev/ruby-assignments01/commit/7eaf705bf027a7829dc12bca914c6152fc41972e
