### ISSUE TITLE
assignment5-todolists/spec/relations_assignment_spec.rb - spec "rq07c" throws undefined method exception

### ISSUE THREAD

**Issue by Hedrig** [rgordeev/ruby-assignments01#14]
Спек rq07c вызывает метод visit, обращаясь к переменной login_path. Однако subject для данного спека не задан, в результате получаем ошибку "undefined local variable or method `login_path' for #RSpec::ExampleGroups::RelationsAssignment::Rq07::Rq07c:0x000000089421d8
Сразу уточню, переменная "login_path" в приложении задана с помощью файла routes.rb:

```
Todolists::Application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end
```

Пожалуйста, внесите исправления в relations_assignment_spec или объясните, как выполнять это задание.

**Comment by rgordeev** [comment]
you haven't defined proper routes mappings yet
http://api.rubyonrails.org/classes/ActionDispatch/Routing.html
