### ISSUE TITLE
 Исправление для rq07b вызывает ошибку в rq09

### ISSUE THREAD

**Issue by Hedrig** [rgordeev/ruby-assignments01#15]
Вы исправили rq07b, разрешив использование данных из seed-файла. Однако спек rq09 в строке
`expect(User.all.to_a.length).to be(4)`
жёстко ограничивает количество записей в seed-файле четырьмя. Вдобавок на содержимое файла в спеке налагаются прочие ограничения, не позволяющие просто изменить данные одной из четырёх записей на нужные:
`expect(User.all.map{ |x| x.username }).to include("Trump", "Fiorina", "Carson", "Clinton")`
Прошу вас исправить эту досадную неполадку.

**Comment by rgordeev** [comment]
Hope this will help you https://github.com/rgordeev/ruby-assignments01/commit/ed03f2562c2d5148817a15a56727a5583e82a1f3
