### ISSUE TITLE
assignment5-todolists/spec/relations_assignment_spec.rb - spec "rq7" отсутствует

### ISSUE THREAD

**Issue by Hedrig** [rgordeev/ruby-assignments01#8]
Либо перепутан порядок, и после rq6 следует rq8, либо rq7 был случайно выброшен (вариант невероятный, но тем не менее). Сам я не уполномочен изменять содержимое папки spec, поэтому создал эту тему.

**Comment by rgordeev** [comment]
Thanks a lot for concern!
Added rq07 to corresponding spec file.
